/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.107
 * Generated at: 2025-07-23 07:57:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1753257440780L));
    _jspx_dependants.put("/menu.jsp", Long.valueOf(1753257385547L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Globalin Mall</title>\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        font-family: 'Helvetica Neue', sans-serif;\r\n");
      out.write("        background-color: #f0f2f5;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        min-height: 100vh;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    header {\r\n");
      out.write("        background-color: #2980b9;\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-size: 1.8em;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    main {\r\n");
      out.write("        flex: 1;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        padding: 40px 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card {\r\n");
      out.write("        background: white;\r\n");
      out.write("        padding: 40px 60px;\r\n");
      out.write("        border-radius: 16px;\r\n");
      out.write("        box-shadow: 0 10px 25px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .icon {\r\n");
      out.write("        font-size: 50px;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        color: #3498db;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h1 {\r\n");
      out.write("        font-size: 2.5em;\r\n");
      out.write("        margin: 10px 0;\r\n");
      out.write("        color: #2c3e50;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h3 {\r\n");
      out.write("        font-size: 1.3em;\r\n");
      out.write("        margin-bottom: 30px;\r\n");
      out.write("        color: #555;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .buttons {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        gap: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn {\r\n");
      out.write("        padding: 12px 24px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        font-size: 1em;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transition: all 0.3s ease;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn.login {\r\n");
      out.write("        background-color: #2980b9;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn.login:hover {\r\n");
      out.write("        background-color: #3498db;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn.signup {\r\n");
      out.write("        background-color: #2ecc71;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn.signup:hover {\r\n");
      out.write("        background-color: #27ae60;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    footer {\r\n");
      out.write("        background-color: #34495e;\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        padding: 15px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- 	    Header\r\n");
      out.write("    <header>\r\n");
      out.write("        🛍️ Globalin Shopping Mall\r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("     -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("     <header class=\"pb-3 mb-4 border-bottom\">\r\n");
      out.write("\r\n");
      out.write("      <a href=\"./welcome.jsp\" class=\"d-flex align-items-center text-dark text-decoration-none\">\r\n");
      out.write("\r\n");
      out.write("      <svg  width=\"32\" height=\"32\" fill=\"currentColor\" class=\"bi bi-house-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("\r\n");
      out.write("   <path d=\"M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L8 2.207l6.646 6.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5Z\"/>\r\n");
      out.write("\r\n");
      out.write("   <path d=\"m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6Z\"/>\r\n");
      out.write("\r\n");
      out.write("</svg>   \r\n");
      out.write("\r\n");
      out.write("        <span class=\"fs-4\">Home</span>\r\n");
      out.write("\r\n");
      out.write("      </a>    \r\n");
      out.write("\r\n");
      out.write("    </header>    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Main Content -->\r\n");
      out.write("    <main>\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"icon\">🛒</div>\r\n");
      out.write("            <h1>Welcome!</h1>\r\n");
      out.write("            <h3>Globalin Marketへようこそ！</h3>\r\n");
      out.write("                        <div class=\"buttons\">\r\n");
      out.write("                <a href=\"login.jsp\" class=\"btn login\">ログイン</a>\r\n");
      out.write("                <a href=\"signup.jsp\" class=\"btn signup\">新規登録</a>\r\n");
      out.write("            </div><br>\r\n");
      out.write("            ");

            	Date day = new Date();
            	String am_pm;
            	
            	int hour = day.getHours(); //시간을 가져오는 메소드
            	int minute = day.getMinutes();  // 분을 가져옴
            	int second	=	day.getSeconds(); // 초를 가져옴
            	
            	if(hour / 12 == 0){
            		am_pm="AM";
            	}else{
            		am_pm="PM";
            		hour = hour-12;
            	}
            	
            	String CT = hour+" : "+minute+" : "+second+" "+am_pm;
            	out.println("현재 접속 시간 "+CT+"\n");
            	
            
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("	    ");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <footer>\r\n");
      out.write("        &copy; 2025 Globalin Market. All rights reserved.\r\n");
      out.write("    </footer>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
